name: yandex_keyboard_desktop
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  http: ^1.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  animated_text_kit: ^4.2.2
  clipboard: ^0.1.3
  win32: ^5.5.1
  hotkey_manager: ^0.2.3
  ffi: ^2.1.2
  logger: ^2.4.0
  tray_manager: ^0.2.3
  google_fonts: ^6.2.1
  fluent_ui: ^4.9.0
  screen_retriever: ^0.1.9
  window_manager: ^0.3.9
  flutter_acrylic: ^1.1.4
  launch_at_startup: ^0.3.1
  provider: any
  package_info_plus: ^4.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  msix: ^3.16.7
  flutter_gen_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

msix_config:
  display_name: Yandex Keyboard Desktop
  msix_version: 1.0.0.0
  store: true
  publisher_display_name: Oniel
  publisher: Oniel
  identity_name: YandexKeyboardDesktop
  app_installer:
    publish_folder_path: c:\msix
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
