name: yandex_keyboard_desktop
description: "A cross-platform text assistant with native selection workflows."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.2.0
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  win32: ^5.5.1
  hotkey_manager: ^0.2.3
  ffi: ^2.2.0
  tray_manager: ^0.2.3
  screen_retriever: ^0.1.9
  window_manager: ^0.3.9
  launch_at_startup: ^0.3.1
  provider: ^6.1.5+1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: any
  lucide_flutter: ^1.23.0
  url_launcher: ^6.3.1

dependency_overrides:
  hotkey_manager_linux:
    path: third_party/hotkey_manager_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/
    - assets/brand/
  generate: true
