name: yandex_keyboard_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  http: ^1.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  animated_text_kit: ^4.2.2
  clipboard: ^0.1.3
  bitsdojo_window: ^0.1.6 
  win32: ^5.5.1
  hotkey_manager: ^0.2.3
  ffi: ^2.1.2
  logger: ^2.4.0
  tray_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true